python ./airflow-dag/product_category_name_translation_test.py -v
python ./airflow-dag/olist_geolocation_dataset_test.py -v
python ./airflow-dag/olist_products_dataset_test.py -v
python ./airflow-dag/olist_sellers_dataset_test.py -v
python ./airflow-dag/olist_customers_dataset_test.py -v
python ./airflow-dag/olist_orders_dataset_test.py -v
python ./airflow-dag/olist_order_items_dataset_test.py -v
python ./airflow-dag/olist_order_payments_dataset_test.py -v
python ./airflow-dag/olist_order_reviews_dataset_test.py -v
